[package]
name = "tg_dice_roller"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
rand = "0.9.0"
regex = "1.11.1"
teloxide = { version = "0.13.0", features = ["macros", "webhooks-axum"] }
pretty_env_logger = "0.5.0"
log = "0.4.20"
